
DROP TABLE IF EXISTS TBL_PENGUINEARS;

CREATE TABLE TBL_PENGUINEARS (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  unit_price DOUBLE NOT NULL,
  cartoon_price INTEGER NOT NULL
);

DROP TABLE IF EXISTS TBL_HORSESHORE;

CREATE TABLE TBL_HORSESHORE (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  unit_price DOUBLE NOT NULL,
  cartoon_price INTEGER NOT NULL
);

